# Generated by Django 2.1.2 on 2018-10-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='topping',
            new_name='toppings',
        ),
    ]
